### ISSUE TITLE
update user endpoint

### ISSUE THREAD

**Issue by kat-hi** [kubeportal/kubeportal#102]
- frontend shows all user emails
- user can change primary email

we need:
PATCH /users/< userID>
request-body: { "primary_email" : "new_primary_email" }
response: updated user object

**Comment by kat-hi** [comment]
@troeger what about these code artifacts?
https://github.com/kubeportal/kubeportal/blob/master/kubeportal/tests/test_api.py#L344-L352
https://github.com/kubeportal/kubeportal/blob/master/kubeportal/api/views.py#L39-L62

-- why does it exist? why isn't it used?
Updating in prod works, where is the logic in the code?

**Comment by troeger** [comment]
This was code that did not work, initially. Feel free to make the next try.

**Comment by kat-hi** [comment]
done https://github.com/kubeportal/kubeportal/pull/113
