### ISSUE TITLE
Faster error handling in sync code

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal#55]
Sync code becomes terribly slow when errors occur during the processing of new KubernetesNamespace objects. Examples where NS names that already exist in the cluster, or incompatible NS names.

**Comment by kat-hi** [comment]
the latest refactoring sessions could slightly improve performance but speed up/parallelization is a bit tricky with the given serial code-logic.

**Comment by kat-hi** [comment]
we should test performance with the next release and talk again...
