### ISSUE TITLE
Approval link in mail should lead to portal login, not admin backend login

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal#67]
Administrators get an email when frontend users click on the "request cluster access" link. The email contains a link to the individual approval page for the user requesting access. This page is part of the admin backend.

When the admin user clicks on the link, and is not already logged-in, the Django needs to perform a redirect to a login page. This login page should be the frontend login page, but currently, the admin user ends up on the Django Admin backend login page. 

A fix should make sure that the frontend login page is used, and that the "next=" redirection still leads the admin user to the correct approval page after entering her credentials.

**Comment by leonardlorenz** [comment]
Redirecting to /logout should be enough.

**Comment by troeger** [comment]
The problem is solved with the recent shift to Django AllAuth. The dedicated admin backend login is completely gone.
