### ISSUE TITLE
Approval request by user should allow choice of admin

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal#68]
Sending all admins an information about every cluster access request does not scale.

The idea would be to allow frontend users a choice from the list of configured admins. Only this person then gets the information email.

**Comment by troeger** [comment]
List of users only shows super users, not admins.

**Comment by troeger** [comment]
Still not working ...

![image](https://user-images.githubusercontent.com/1308795/91877289-1a547b00-ec7e-11ea-8174-8e75e05b79df.png)

**Comment by troeger** [comment]
Check views.py, line 73 vs. 201.

**Comment by leonardlorenz** [comment]
I have fixed this issue now. Do you think we should show the root user in the drop down? I think only showing staff members which aren't root would make more sense, right?

**Comment by troeger** [comment]
Root should not show up, the account is only intended for initial setup and emergency operations.
