### ISSUE TITLE
Prune buttons

### ISSUE THREAD

**Issue by leonardlorenz** [kubeportal/kubeportal#85]
- for users that haven't logged in for a long time.
- for namespaces without pods
- for namespaces without assigned users

**Comment by leonardlorenz** [comment]
I would put these under the related lists in the clean up view. Are there any other requirements? How would you realize this @troeger ?

**Comment by leonardlorenz** [comment]
I've worked out an initial implementation of this in the prune-buttons branch. The buttons are functional. I will have to write some tests for this still.

![This is what it currently looks like.](https://leonardlorenz.de/files/2020-09-16_19-53-01.png)

I'm considering to add selector ticks for each element in the tables later on. Do you think this would be useful? The current implementation will just purge every element in the respective table.

Another problem I've encountered is that I'm not really able to load the bootstrap css in the header of templates/base.html. Hence the button styling is currently done inside a <style> tag in the template (yikes...). Is there a way to hook into the default django admin templates without overwriting the files? I'll investigate some more.

**Comment by troeger** [comment]
Selectors sound like a good idea. I would recommend to rely on the existing deletion confirmation page in Django.

Overriding Django admin templates typically relies on copying the originals and putting them in "templates/admin" in the project. This is described somewhere in the Django docs.

**Comment by leonardlorenz** [comment]
I have implemented the selectors and also some select all buttons, since I can imagine clicking through hundreds will become annoying.

Also it will ask for confirmation using djangos confirm().

I will implement tests now. My by-hand testing shows they work already though.

![New prune buttons with select all button](https://leonardlorenz.de/screenshots/2020-09-23_13-41-08.png)
